### PR TITLE
Fix spelling mistakes. Fetc should be Fetch

### PR DESCRIPTION
**Pull request by rclanan**
Fork and cloned this to fix them all in a single pull request. The others were done through the browser and it wasn't building properly since it wasn't changed in both places together.

### CODE REVIEW

**Comment by rclanan** [comment]
Here is a combined pull request with all the changes together that should allow the build to pass.

**Comment by benmanbs** [comment]
Sweet! I'll merge this in once the tests pass.

**Comment by rclanan** [comment]
There we go, sorry about all the confusion. I was just browsing the code from your article. And tried to do the pull request from there. Saw it failed and decided to do a proper pull request when I got back home.

**Comment by benmanbs** [comment]
Merged! Thanks!

**Pull request merged**
